### ISSUE TITLE
Connection Time out Errors

### ISSUE THREAD

**Issue by starhound** [jadolg/RocketChatBot#9]
Traceback (most recent call last):
  File "partsbot.py", line 124, in <module>
    bot.run()
  File "/home/wesley/.local/lib/python3.8/site-packages/RocketChatBot.py", line 148, in run
    for channel in self.api.channels_list_joined().json().get('channels'):
  File "/home/wesley/.local/lib/python3.8/site-packages/rocketchat_API/rocketchat.py", line 293, in channels_list_joined
    return self.__call_api_get('channels.list.joined', kwargs=kwargs)
  File "/home/wesley/.local/lib/python3.8/site-packages/rocketchat_API/rocketchat.py", line 50, in __call_api_get
    return self.req.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mydomain.com', port=443): Read timed out. (read timeout=30)

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wesley/.local/lib/python3.8/site-packages/RocketChatBot.py", line 120, in process_channel
    self.process_messages(self.api.channels_history(channel_id, oldest=self.lastts[channel_id]).json(),
  File "/home/wesley/.local/lib/python3.8/site-packages/rocketchat_API/rocketchat.py", line 306, in channels_history
    return self.__call_api_get('channels.history', roomId=room_id, kwargs=kwargs)
  File "/home/wesley/.local/lib/python3.8/site-packages/rocketchat_API/rocketchat.py", line 50, in __call_api_get
    return self.req.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='mydomain.com', port=443): Max retries exceeded with url: /api/v1/channels.history?roomId=LcxSQKEqEKNZJB3u5&oldest=2020-07-15T17:01:31.149Z (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa4782d74f0>, 'Connection to mydomain.com timed out. (connect timeout=30)'))

Seems to happen randomly.

**Comment by jadolg** [comment]
Probably limited by the API rate-limiting mechanism. This is not the best way to do a bot if you want to manage a large number of channels. Check this one up https://github.com/jadolg/annoying_orange_bot for a better way.

**Comment by starhound** [comment]
Our API and DDP limiters have been disabled since project deployment.

We believe it was a network issue that kept causing the connection to be lost as we reset our sonicwall after noticing connectivity issues in other business applications, which seems to have stopped the errors. 

What I ended up doing was wrapping some of these bot functions in try/except blocks to prevent the full error being posted to the terminal as I have the bot itself running via Popen() so it'll always reconnect, ect.

We use your bot to manage a single channel that is for our parts ordering department and it works flawlessly after some minor adjustments! I imagine future expansions we can simply run different instances of the bot itself. Thanks for your time & best of luck.
